# crates/mid-math/Cargo.toml
[package]
name        = "mid-math"
version     = "0.1.0"
edition     = "2021"
description = "SIMD-aligned math primitives for Mid Engine — FFI-ready, cross-platform"

[lib]
name = "mid_math"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]

[dev-dependencies]
criterion   = { version = "0.5", features = ["html_reports"] }
glam        = { version = "0.28", features = [] }
nalgebra    = { version = "0.33" }
ultraviolet = { version = "0.9" }

[[bench]]
name    = "vs_glam"
harness = false


[[bench]]
name    = "vs_all"
harness = false

[features]
default = []
simd    = []
