[workspace]
members = [
    "crates/mid-log",
    "crates/mid-net",
    "crates/mid-net/wire",
    "crates/mid-net/transport",
    "crates/mid-net/reliable",
    "crates/mid-ecs",
    "crates/mid-math",
    "crates/mid-geom",
    "crates/mid-common",
    "crates/mid-trace",
    "tools/mdix-compiler",
    "examples/headless-server",
    "examples/custom-transport-demo",
]
resolver = "2"

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true
debug         = false
