[package]
name = "mid-net-transport-quinn"
version = "0.1.0"
edition = "2021"

[lib]
name = "mid_net_transport_quinn"

[dependencies]
mid-net-transport = { path = "../transport" }
web-transport-quinn = "0.11"
bytes = "1"
tokio = { version = "1", default-features = false, features = ["rt", "sync"] }
