# crates/mid-log/Cargo.toml
[package]
name        = "mid-log"
version     = "0.1.0"
edition     = "2021"
description = "Non-blocking tiered logger for Mid Engine — FFI-ready, cross-platform"

[lib]
name = "mid_log"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
crossbeam-channel = "0.5"

[dev-dependencies]
criterion          = { version = "0.5", features = ["html_reports"] }
log                = "0.4"
env_logger         = "0.11"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
slog       = "2"
slog-async = "2"
slog-term  = "2"
fast_log   = "1"
[[bench]]
name    = "vs_baseline"
harness = false

[features]
default        = []
backtrace      = []
android-logcat = []
