// crates/mid-geom/benches/geometry.rs
//! Geometry benchmark suite.
//!
//! Three measurement priorities per the engine design doc:
//!
//!   1. Early-exit efficiency — miss cases must be FASTER than hit cases.
//!      A well-implemented AABB test exits the moment it finds a separating
//!      axis; a sphere test never calls sqrt at all (squared distance compare).
//!
//!   2. Avoidance of expensive math — no sqrt in boolean overlap tests,
//!      no division in AABB/plane tests.
//!
//!   3. Randomised data — all inputs are generated by a deterministic PRNG
//!      (inline xorshift64) so the compiler cannot fold constants and the CPU
//!      cannot use perfect branch prediction.
//!
//! Layout:
//!   micro/   — single-pair tests (ns-level, measures ALU cost per call)
//!   bulk/    — 100 k entity sweeps (µs-level, measures cache + pipeline cost)
//!   ray/     — parametric intersection tests

use criterion::{
    black_box, criterion_group, criterion_main, BenchmarkId, Criterion, Throughput,
};

use mid_geom::{AABB, Capsule, Circle, Frustum, Plane, Ray2, Ray3, Rect, Sphere};
use mid_math::{Mat4, Quat, Vec2, Vec3, FRAC_PI_4};

// ── Deterministic pseudo-random number generator ──────────────────────────────
//
// Xorshift64 — no external crates needed, same seed every run so results are
// reproducible, but varied enough that the compiler cannot fold anything.

struct Xorshift(u64);

impl Xorshift {
    const fn new() -> Self { Self(0x517cc1b727220a95) }

    #[inline(always)]
    fn next_u64(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    /// f32 in [0, 1).
    #[inline(always)]
    fn f32(&mut self) -> f32 {
        (self.next_u64() >> 40) as f32 / (1u64 << 24) as f32
    }

    /// f32 in [lo, hi).
    #[inline(always)]
    fn range(&mut self, lo: f32, hi: f32) -> f32 {
        lo + self.f32() * (hi - lo)
    }

    #[inline(always)]
    fn vec3(&mut self, lo: f32, hi: f32) -> Vec3 {
        Vec3::new(self.range(lo, hi), self.range(lo, hi), self.range(lo, hi))
    }

    #[inline(always)]
    fn vec2(&mut self, lo: f32, hi: f32) -> Vec2 {
        Vec2::new(self.range(lo, hi), self.range(lo, hi))
    }

    /// Unit quaternion — normalised axis-angle with random axis and angle.
    fn quat(&mut self) -> Quat {
        let axis = self.vec3(-1.0, 1.0).normalize();
        let angle = self.range(0.0, core::f32::consts::TAU);
        Quat::from_axis_angle(axis, angle)
    }
}

// ── Data sets (generated once, reused across all benchmarks) ─────────────────

const N: usize = 100_000;

struct DataSets {
    aabbs:      Vec<AABB>,
    spheres:    Vec<Sphere>,
    capsules:   Vec<Capsule>,
    rects:      Vec<Rect>,
    circles:    Vec<Circle>,
    rays3:      Vec<Ray3>,
    rays2:      Vec<Ray2>,
    /// View-projection matrix for frustum culling benches.
    view_proj:  Mat4,
    frustum:    Frustum,
}

impl DataSets {
    fn build() -> Self {
        let mut rng = Xorshift::new();

        // AABBs clustered around origin with half-extents in [0.5, 5.0].
        let aabbs: Vec<AABB> = (0..N).map(|_| {
            let center = rng.vec3(-100.0, 100.0);
            let half   = rng.vec3(0.5, 5.0);
            AABB::new(center - half, center + half)
        }).collect();

        let spheres: Vec<Sphere> = (0..N).map(|_| {
            Sphere::new(rng.vec3(-100.0, 100.0), rng.range(0.5, 5.0))
        }).collect();

        let capsules: Vec<Capsule> = (0..N).map(|_| {
            let base   = rng.vec3(-100.0, 100.0);
            let tip    = base + rng.vec3(-3.0, 3.0);
            let radius = rng.range(0.3, 2.0);
            Capsule::new(base, tip, radius)
        }).collect();

        let rects: Vec<Rect> = (0..N).map(|_| {
            let center = rng.vec2(-100.0, 100.0);
            let half   = rng.vec2(0.5, 10.0);
            Rect::from_center_half_extents(center, half)
        }).collect();

        let circles: Vec<Circle> = (0..N).map(|_| {
            Circle::new(rng.vec2(-100.0, 100.0), rng.range(0.5, 5.0))
        }).collect();

        let rays3: Vec<Ray3> = (0..N).map(|_| {
            let origin = rng.vec3(-50.0, 50.0);
            let dir    = rng.vec3(-1.0, 1.0).normalize();
            Ray3::new_unnormalized(origin, dir)
        }).collect();

        let rays2: Vec<Ray2> = (0..N).map(|_| {
            let origin = rng.vec2(-50.0, 50.0);
            let dir    = rng.vec2(-1.0, 1.0).normalize();
            Ray2::new_unnormalized(origin, dir)
        }).collect();

        // Perspective frustum looking down -Z from origin, 90° FOV.
        let view_proj = Mat4::perspective_rh(FRAC_PI_4 * 2.0, 16.0 / 9.0, 0.1, 1000.0)
            * Mat4::look_at_rh(
                Vec3::new(0.0, 10.0, 100.0),
                Vec3::ZERO,
                Vec3::Y,
            );
        let frustum = Frustum::from_mat4(&view_proj);

        Self { aabbs, spheres, capsules, rects, circles, rays3, rays2, view_proj, frustum }
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Build a pair of AABBs that are guaranteed to overlap.
fn overlapping_aabbs(rng: &mut Xorshift) -> (AABB, AABB) {
    let c1 = rng.vec3(-50.0, 50.0);
    let c2 = c1 + rng.vec3(-0.5, 0.5); // centre offset < half-extent → always overlap
    let h  = rng.vec3(1.0, 3.0);
    (
        AABB::new(c1 - h, c1 + h),
        AABB::new(c2 - h, c2 + h),
    )
}

/// Build a pair of AABBs that are guaranteed to NOT overlap.
fn separated_aabbs(rng: &mut Xorshift) -> (AABB, AABB) {
    let c1 = rng.vec3(-50.0, 50.0);
    let c2 = c1 + Vec3::new(20.0, 0.0, 0.0); // far apart on X — immediate early-exit
    let h  = rng.vec3(0.5, 2.0);
    (
        AABB::new(c1 - h, c1 + h),
        AABB::new(c2 - h, c2 + h),
    )
}

// ═════════════════════════════════════════════════════════════════════════════
// MICRO BENCHMARKS — single pair, measures raw ALU cost per call
// ═════════════════════════════════════════════════════════════════════════════

fn bench_aabb_micro(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("micro/aabb");

    // Hit path — both AABBs overlap on all three axes.
    // No early exit; all six comparisons execute.
    let (a, b) = overlapping_aabbs(&mut rng);
    g.bench_function("intersects_aabb/hit", |bench| {
        bench.iter(|| black_box(black_box(a).intersects_aabb(black_box(&b))))
    });

    // Miss path — separated on X axis → exits after first axis check.
    // Should be measurably faster than hit path.
    let (a, b) = separated_aabbs(&mut rng);
    g.bench_function("intersects_aabb/miss", |bench| {
        bench.iter(|| black_box(black_box(a).intersects_aabb(black_box(&b))))
    });

    g.bench_function("contains_point", |bench| {
        let aabb = rng.vec3(-5.0, 5.0);
        let half = rng.vec3(1.0, 3.0);
        let b = AABB::new(aabb - half, aabb + half);
        let p = rng.vec3(-8.0, 8.0);
        bench.iter(|| black_box(black_box(b).contains_point(black_box(p))))
    });

    g.bench_function("closest_point", |bench| {
        let c = rng.vec3(-5.0, 5.0);
        let h = rng.vec3(1.0, 3.0);
        let b = AABB::new(c - h, c + h);
        let p = rng.vec3(-10.0, 10.0);
        bench.iter(|| black_box(black_box(b).closest_point(black_box(p))))
    });

    g.bench_function("signed_distance", |bench| {
        let c = rng.vec3(-5.0, 5.0);
        let h = rng.vec3(1.0, 3.0);
        let b = AABB::new(c - h, c + h);
        let p = rng.vec3(-10.0, 10.0);
        bench.iter(|| black_box(black_box(b).signed_distance(black_box(p))))
    });

    g.bench_function("merge", |bench| {
        let (a, b) = overlapping_aabbs(&mut rng);
        bench.iter(|| black_box(black_box(a).merge(black_box(b))))
    });

    g.finish();
}

fn bench_sphere_micro(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("micro/sphere");

    // Sphere-sphere uses squared distance — never calls sqrt.
    // Hit and miss variants should be nearly identical cost (no branch to exploit).
    let s1 = Sphere::new(Vec3::ZERO, 2.0);
    let s2_hit  = Sphere::new(Vec3::new(1.0, 0.0, 0.0), 2.0); // overlap
    let s2_miss = Sphere::new(Vec3::new(10.0, 0.0, 0.0), 1.0); // separated

    g.bench_function("intersects_sphere/hit", |bench| {
        bench.iter(|| black_box(black_box(s1).intersects_sphere(black_box(&s2_hit))))
    });
    g.bench_function("intersects_sphere/miss", |bench| {
        bench.iter(|| black_box(black_box(s1).intersects_sphere(black_box(&s2_miss))))
    });

    // Sphere vs AABB — uses squared distance to nearest point on box.
    let aabb = AABB::new(Vec3::splat(-2.0), Vec3::splat(2.0));
    let s_in  = Sphere::new(Vec3::new(0.5, 0.0, 0.0), 1.0);
    let s_out = Sphere::new(Vec3::new(10.0, 0.0, 0.0), 1.0);

    g.bench_function("intersects_aabb/hit", |bench| {
        bench.iter(|| black_box(black_box(aabb).intersects_sphere(black_box(&s_in))))
    });
    g.bench_function("intersects_aabb/miss", |bench| {
        bench.iter(|| black_box(black_box(aabb).intersects_sphere(black_box(&s_out))))
    });

    g.bench_function("signed_distance", |bench| {
        let s = Sphere::new(rng.vec3(-5.0, 5.0), rng.range(0.5, 3.0));
        let p = rng.vec3(-10.0, 10.0);
        bench.iter(|| black_box(black_box(s).signed_distance(black_box(p))))
    });

    g.bench_function("bounding_aabb", |bench| {
        let s = Sphere::new(rng.vec3(-5.0, 5.0), rng.range(0.5, 3.0));
        bench.iter(|| black_box(black_box(s).bounding_aabb()))
    });

    g.finish();
}

fn bench_capsule_micro(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("micro/capsule");

    let cap1 = Capsule::new(Vec3::ZERO, Vec3::Y * 2.0, 0.5);
    let cap2_hit  = Capsule::new(Vec3::new(0.8, 0.5, 0.0), Vec3::new(0.8, 2.5, 0.0), 0.5);
    let cap2_miss = Capsule::new(Vec3::new(5.0, 0.0, 0.0), Vec3::new(5.0, 2.0, 0.0), 0.3);
    let sph_hit   = Sphere::new(Vec3::new(0.0, 1.0, 0.4), 0.5);
    let sph_miss  = Sphere::new(Vec3::new(5.0, 0.0, 0.0), 0.3);

    g.bench_function("intersects_capsule/hit", |bench| {
        bench.iter(|| black_box(black_box(cap1).intersects_capsule(black_box(&cap2_hit))))
    });
    g.bench_function("intersects_capsule/miss", |bench| {
        bench.iter(|| black_box(black_box(cap1).intersects_capsule(black_box(&cap2_miss))))
    });
    g.bench_function("intersects_sphere/hit", |bench| {
        bench.iter(|| black_box(black_box(cap1).intersects_sphere(black_box(&sph_hit))))
    });
    g.bench_function("intersects_sphere/miss", |bench| {
        bench.iter(|| black_box(black_box(cap1).intersects_sphere(black_box(&sph_miss))))
    });

    g.bench_function("closest_point_on_axis", |bench| {
        let cap = Capsule::new(rng.vec3(-3.0, 3.0), rng.vec3(-3.0, 3.0), 0.5);
        let p   = rng.vec3(-5.0, 5.0);
        bench.iter(|| black_box(black_box(cap).closest_point_on_axis(black_box(p))))
    });

    g.finish();
}

fn bench_plane_micro(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("micro/plane");

    let plane = Plane::from_normal_point(Vec3::Y, Vec3::ZERO);
    let p_front  = Vec3::new(0.0,  1.0, 0.0);
    let p_behind = Vec3::new(0.0, -1.0, 0.0);

    g.bench_function("signed_distance/front", |bench| {
        bench.iter(|| black_box(black_box(plane).signed_distance(black_box(p_front))))
    });
    g.bench_function("signed_distance/behind", |bench| {
        bench.iter(|| black_box(black_box(plane).signed_distance(black_box(p_behind))))
    });
    g.bench_function("project_point", |bench| {
        let p = rng.vec3(-5.0, 5.0);
        bench.iter(|| black_box(black_box(plane).project_point(black_box(p))))
    });
    g.bench_function("classify", |bench| {
        let p = rng.vec3(-5.0, 5.0);
        bench.iter(|| black_box(black_box(plane).classify(black_box(p))))
    });

    g.finish();
}

fn bench_rect_micro(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("micro/rect");

    let r1 = Rect::new(Vec2::ZERO, Vec2::splat(4.0));
    let r2_hit  = Rect::new(Vec2::splat(2.0), Vec2::splat(6.0));
    let r2_miss = Rect::new(Vec2::splat(10.0), Vec2::splat(14.0));

    g.bench_function("intersects_rect/hit", |bench| {
        bench.iter(|| black_box(black_box(r1).intersects_rect(black_box(r2_hit))))
    });
    g.bench_function("intersects_rect/miss", |bench| {
        bench.iter(|| black_box(black_box(r1).intersects_rect(black_box(r2_miss))))
    });

    g.bench_function("contains_point", |bench| {
        let p = rng.vec2(-8.0, 8.0);
        bench.iter(|| black_box(black_box(r1).contains_point(black_box(p))))
    });

    g.bench_function("merge", |bench| {
        let (a, b) = (
            Rect::from_center_half_extents(rng.vec2(-5.0, 5.0), rng.vec2(1.0, 3.0)),
            Rect::from_center_half_extents(rng.vec2(-5.0, 5.0), rng.vec2(1.0, 3.0)),
        );
        bench.iter(|| black_box(black_box(a).merge(black_box(b))))
    });

    g.finish();
}

// ═════════════════════════════════════════════════════════════════════════════
// RAY BENCHMARKS — parametric intersection
// ═════════════════════════════════════════════════════════════════════════════

fn bench_ray3(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("ray3");

    // Ray aimed directly at the target — guaranteed hit.
    let target_aabb   = AABB::new(Vec3::splat(-1.0), Vec3::splat(1.0));
    let target_sphere = Sphere::new(Vec3::ZERO, 1.5);
    let target_cap    = Capsule::new(Vec3::new(0.0, -1.0, 0.0), Vec3::new(0.0, 1.0, 0.0), 0.5);
    let ground_plane  = Plane::from_normal_point(Vec3::Y, Vec3::ZERO);

    let ray_hit = Ray3::new_unnormalized(Vec3::new(0.0, 0.0, 5.0), Vec3::NEG_Z);
    let ray_miss = Ray3::new_unnormalized(Vec3::new(10.0, 10.0, 5.0), Vec3::NEG_Z);

    g.bench_function("vs_aabb/hit", |bench| {
        bench.iter(|| black_box(black_box(ray_hit).intersect_aabb(black_box(&target_aabb))))
    });
    g.bench_function("vs_aabb/miss", |bench| {
        bench.iter(|| black_box(black_box(ray_miss).intersect_aabb(black_box(&target_aabb))))
    });

    g.bench_function("vs_sphere/hit", |bench| {
        bench.iter(|| black_box(black_box(ray_hit).intersect_sphere(black_box(&target_sphere))))
    });
    g.bench_function("vs_sphere/miss", |bench| {
        bench.iter(|| black_box(black_box(ray_miss).intersect_sphere(black_box(&target_sphere))))
    });

    g.bench_function("vs_capsule/hit", |bench| {
        bench.iter(|| black_box(black_box(ray_hit).intersect_capsule(black_box(&target_cap))))
    });
    g.bench_function("vs_capsule/miss", |bench| {
        bench.iter(|| black_box(black_box(ray_miss).intersect_capsule(black_box(&target_cap))))
    });

    g.bench_function("vs_plane", |bench| {
        let origin = rng.vec3(-10.0, 10.0);
        let dir    = rng.vec3(-1.0, 1.0).normalize();
        let r = Ray3::new_unnormalized(origin, dir);
        bench.iter(|| black_box(black_box(r).intersect_plane(black_box(&ground_plane))))
    });

    g.finish();
}

fn bench_ray2(c: &mut Criterion) {
    let mut rng = Xorshift::new();
    let mut g = c.benchmark_group("ray2");

    let target_rect   = Rect::new(Vec2::splat(-2.0), Vec2::splat(2.0));
    let target_circle = Circle::new(Vec2::ZERO, 2.0);
    let ray_hit  = Ray2::new_unnormalized(Vec2::new(0.0, 5.0), Vec2::new(0.0, -1.0));
    let ray_miss = Ray2::new_unnormalized(Vec2::new(10.0, 5.0), Vec2::new(0.0, -1.0));

    g.bench_function("vs_rect/hit", |bench| {
        bench.iter(|| black_box(black_box(ray_hit).intersect_rect(black_box(&target_rect))))
    });
    g.bench_function("vs_rect/miss", |bench| {
        bench.iter(|| black_box(black_box(ray_miss).intersect_rect(black_box(&target_rect))))
    });
    g.bench_function("vs_circle/hit", |bench| {
        bench.iter(|| black_box(black_box(ray_hit).intersect_circle(black_box(&target_circle))))
    });
    g.bench_function("vs_circle/miss", |bench| {
        bench.iter(|| black_box(black_box(ray_miss).intersect_circle(black_box(&target_circle))))
    });

    g.finish();
}

// ═════════════════════════════════════════════════════════════════════════════
// BULK BENCHMARKS — 100 k entities, measures cache + pipeline behaviour
// ═════════════════════════════════════════════════════════════════════════════

fn bench_bulk_frustum_cull(c: &mut Criterion) {
    let ds = DataSets::build();
    let mut g = c.benchmark_group("bulk/frustum_cull");
    g.throughput(Throughput::Elements(N as u64));

    // AABB frustum culling — the bread-and-butter of a render loop.
    // Each AABB is tested against 6 planes (positive-vertex method).
    // ~80-90% of AABBs will be outside the frustum → lots of early exits.
    g.bench_function("aabb_100k", |bench| {
        bench.iter(|| {
            let mut visible = 0u32;
            for aabb in &ds.aabbs {
                if ds.frustum.intersects_aabb(black_box(aabb)) {
                    visible += 1;
                }
            }
            black_box(visible)
        })
    });

    g.bench_function("sphere_100k", |bench| {
        bench.iter(|| {
            let mut visible = 0u32;
            for s in &ds.spheres {
                if ds.frustum.intersects_sphere(black_box(s)) {
                    visible += 1;
                }
            }
            black_box(visible)
        })
    });

    g.finish();
}

fn bench_bulk_aabb_pairs(c: &mut Criterion) {
    let ds = DataSets::build();
    let mut g = c.benchmark_group("bulk/aabb_pairs");
    g.throughput(Throughput::Elements(N as u64));

    // Consecutive-pair test — simulates broadphase checking sorted pairs.
    // Real broadphase generates sorted pairs; consecutive in our list gives
    // a realistic ~50% hit rate.
    g.bench_function("consecutive_pairs_100k", |bench| {
        bench.iter(|| {
            let mut hits = 0u32;
            for i in (0..N - 1).step_by(2) {
                if ds.aabbs[i].intersects_aabb(black_box(&ds.aabbs[i + 1])) {
                    hits += 1;
                }
            }
            black_box(hits)
        })
    });

    g.finish();
}

fn bench_bulk_sphere_pairs(c: &mut Criterion) {
    let ds = DataSets::build();
    let mut g = c.benchmark_group("bulk/sphere_pairs");
    g.throughput(Throughput::Elements(N as u64));

    // Key metric: sphere-sphere must NEVER call sqrt.
    // Compare: d² ≤ (r₁+r₂)² is a pure multiply-add chain.
    g.bench_function("consecutive_pairs_100k", |bench| {
        bench.iter(|| {
            let mut hits = 0u32;
            for i in (0..N - 1).step_by(2) {
                if ds.spheres[i].intersects_sphere(black_box(&ds.spheres[i + 1])) {
                    hits += 1;
                }
            }
            black_box(hits)
        })
    });

    g.finish();
}

fn bench_bulk_ray3(c: &mut Criterion) {
    let ds = DataSets::build();
    let mut g = c.benchmark_group("bulk/ray3");
    g.throughput(Throughput::Elements(N as u64));

    // Shoot each ray against the AABB at the same index.
    // Mixed hit/miss ratio determined by random placement.
    g.bench_function("vs_aabb_100k", |bench| {
        bench.iter(|| {
            let mut hits = 0u32;
            for (ray, aabb) in ds.rays3.iter().zip(ds.aabbs.iter()) {
                if ray.intersect_aabb(black_box(aabb)).is_some() {
                    hits += 1;
                }
            }
            black_box(hits)
        })
    });

    g.bench_function("vs_sphere_100k", |bench| {
        bench.iter(|| {
            let mut hits = 0u32;
            for (ray, s) in ds.rays3.iter().zip(ds.spheres.iter()) {
                if ray.intersect_sphere(black_box(s)).is_some() {
                    hits += 1;
                }
            }
            black_box(hits)
        })
    });

    g.finish();
}

// ── Criterion entry points ────────────────────────────────────────────────────

criterion_group!(
    micro,
    bench_aabb_micro,
    bench_sphere_micro,
    bench_capsule_micro,
    bench_plane_micro,
    bench_rect_micro,
);

criterion_group!(
    rays,
    bench_ray3,
    bench_ray2,
);

criterion_group!(
    bulk,
    bench_bulk_frustum_cull,
    bench_bulk_aabb_pairs,
    bench_bulk_sphere_pairs,
    bench_bulk_ray3,
);

criterion_main!(micro, rays, bulk);
